---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_ubuntu_2004
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: ubuntu2004

verifier:
  name: testinfra
  directory: ../default/tests