name: "molecule tests"

on:
  push:
    branches:
      - main
  

env:
  MOLECULEW_USE_SYSTEM: 'true'
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  test:
    name: Molecule test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ansible-version:
          - '2.10.7' 
        molecule-scenario:
          - ubuntu2004
    env:
      MOLECULEW_ANSIBLE: ${{ matrix.ansible-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Cache Molecule
        id: molecule-cache
        uses: actions/cache@v2
        with:
          path: ~/.moleculew
          key: Ansible-${{ matrix.ansible-version }}-${{ hashFiles('.moleculew/**') }}          

      - name: Install dependencies
        if: steps.molecule-cache.outputs.cache-hit != 'true'
        run: ./moleculew wrapper-install

      - name: Dependency versions
        run: ./moleculew wrapper-versions

      - name: Molecule test 
        run: ./moleculew test --scenario-name=${{ matrix.molecule-scenario }}
