name: "molecule tests"

on:
  push:
    branches:
      - main
  

env:
  MOLECULEW_USE_SYSTEM: 'true'
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  test:
    name: Molecule test
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ansible-version:
          - '2.10.7' # max-ansible-test-version
        molecule-scenario:
          - ubuntu_max
    env:
      MOLECULEW_ANSIBLE: ${{ matrix.ansible-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'


